development:
  adapter: postgresql
  encoding: unicode
  database: streetmom_development
  pool: 5
  # username: streetmom
  # password:
  # host: localhost

test: &test
  adapter: postgresql
  encoding: unicode
  database: streetmom_test
  pool: 5
  # username: streetmom
  # password:

production:
  adapter: postgresql
  encoding: unicode
  database: streetmom_production
  pool: 5
  username: streetmom
  password:

cucumber:
  <<: *test
